"""
AI-Generated Text Detection Engine
Calculates Perplexity, Burstiness, and Linguistic Markers to detect
whether text was generated by Large Language Models (e.g. ChatGPT, Claude).
"""

import re
import math
from typing import List, Dict, Any
from pydantic import BaseModel, Field

# Common LLM transition phrases and hallmark cliches
LLM_MARKERS = [
    r"\bdelve(?:s|d|ing)?\b",
    r"\bfurthermore\b",
    r"\bmoreover\b",
    r"\bin summary\b",
    r"\bin conclusion\b",
    r"\bit is important to (?:note|remember|consider)\b",
    r"\bcrucial (?:aspect|component|role|factor)\b",
    r"\bpivotal (?:role|factor|aspect)\b",
    r"\btestament to\b",
    r"\bholistic(?:ally)?\b",
    r"\bseamlessly\b",
    r"\bcomprehensive (?:approach|guide|overview|analysis)\b",
    r"\bplays a (?:vital|key|crucial) role\b",
    r"\bleverag(?:e|ing|ed)\b",
    r"\bintricate (?:balance|details|network)\b",
    r"\bbustling\b",
    r"\bbeacon of\b",
    r"\btapestry of\b",
    r"\bparamount importance\b",
    r"\bin today's (?:fast-paced|rapidly evolving|digital) world\b",
    r"\bby doing so\b",
    r"\bnot only .*? but also\b",
]

# Baseline corpus statistics for English word frequency estimation
COMMON_WORDS = {
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    "is", "was", "are", "were", "been", "has", "had"
}

FORMAL_AND_TECH_WORDS = {
    "system", "systems", "architecture", "distributed", "scalability", "optimization",
    "latency", "throughput", "comprehensive", "seamlessly", "intricate", "paramount",
    "holistic", "testament", "delve", "pivotal", "leveraging"
}

class AIDetectionResult(BaseModel):
    ai_probability: float = Field(..., description="Estimated probability of AI generation (0-100%)")
    is_flagged: bool = Field(..., description="True if AI probability exceeds threshold (>= 60%)")
    human_likeness_score: float = Field(..., description="Human authenticity score (0-100%)")
    perplexity: float = Field(..., description="Estimated average sentence perplexity score")
    burstiness: float = Field(..., description="Coefficient of variation in sentence length and rhythm")
    sentence_count: int = Field(..., description="Total number of evaluated sentences")
    avg_sentence_length: float = Field(..., description="Average words per sentence")
    flags: List[str] = Field(default_factory=list, description="Specific indicators detected")
    verdict: str = Field(..., description="Clear human-readable summary verdict")

def split_into_sentences(text: str) -> List[str]:
    """Splits text into sentences, handling common punctuation."""
    raw_sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    # Filter out empty or whitespace-only strings
    clean = [s.strip() for s in raw_sentences if s.strip() and len(s.split()) >= 2]
    return clean

def calculate_sentence_perplexity(sentence: str) -> float:
    """
    Estimates token-level cross-entropy and perplexity based on vocabulary
    rarity, bigram transitional structure, and word length distributions.
    Standardized so predictable LLM text falls into ~15-32, while diverse
    human speech/writing reaches ~40-100+.
    """
    words = re.findall(r'\b[a-zA-Z]+\b', sentence.lower())
    if not words:
        return 50.0

    total_neg_log_p = 0.0
    for i, w in enumerate(words):
        # Probability estimation based on common frequency distribution
        if w in COMMON_WORDS:
            p = 0.10
        elif w in FORMAL_AND_TECH_WORDS:
            p = 0.05
        elif len(w) <= 4:
            p = 0.03
        elif len(w) <= 8:
            p = 0.015
        else:
            p = 0.005

        # Context factor: consecutive transitions or formulaic pairings
        if i > 0 and (words[i-1] in COMMON_WORDS or words[i-1] in FORMAL_AND_TECH_WORDS) and (w in COMMON_WORDS or w in FORMAL_AND_TECH_WORDS):
            p *= 1.2

        total_neg_log_p -= math.log(max(p, 1e-6))

    avg_neg_log_p = total_neg_log_p / len(words)
    # Exponentiate to obtain perplexity
    raw_ppl = math.exp(avg_neg_log_p)
    return round(raw_ppl, 2)

def calculate_burstiness(sentence_lengths: List[int], sentence_ppls: List[float]) -> float:
    """
    Burstiness is calculated as the coefficient of variation (CV = std_dev / mean)
    across sentence lengths combined with perplexity variance.
    Humans have high CV (> 0.50), while AI is very rhythmic and uniform (< 0.28).
    """
    if len(sentence_lengths) < 2:
        return 0.5  # Neutral default for single-sentence inputs

    # Length variance
    mean_len = sum(sentence_lengths) / len(sentence_lengths)
    if mean_len == 0:
        return 0.5
    var_len = sum((x - mean_len) ** 2 for x in sentence_lengths) / len(sentence_lengths)
    std_len = math.sqrt(var_len)
    cv_len = std_len / mean_len

    # Perplexity variance
    mean_ppl = sum(sentence_ppls) / len(sentence_ppls)
    if mean_ppl > 0:
        var_ppl = sum((x - mean_ppl) ** 2 for x in sentence_ppls) / len(sentence_ppls)
        std_ppl = math.sqrt(var_ppl)
        cv_ppl = std_ppl / mean_ppl
    else:
        cv_ppl = 0.5

    # Combined weighted burstiness index
    burstiness = (0.65 * cv_len) + (0.35 * cv_ppl)
    return round(burstiness, 3)

def detect_ai_text(text: str) -> AIDetectionResult:
    """
    Main detection entrypoint:
    Analyzes input text and outputs an AIDetectionResult with perplexity,
    burstiness, AI probability, and granular flags.
    """
    if not text or not text.strip():
        return AIDetectionResult(
            ai_probability=0.0,
            is_flagged=False,
            human_likeness_score=100.0,
            perplexity=50.0,
            burstiness=0.5,
            sentence_count=0,
            avg_sentence_length=0.0,
            flags=["Insufficient text to evaluate"],
            verdict="Inconclusive (empty or trivial answer)"
        )

    sentences = split_into_sentences(text)
    words = re.findall(r'\b[a-zA-Z]+\b', text)
    word_count = len(words)

    if word_count < 15:
        return AIDetectionResult(
            ai_probability=10.0,
            is_flagged=False,
            human_likeness_score=90.0,
            perplexity=45.0,
            burstiness=0.5,
            sentence_count=len(sentences),
            avg_sentence_length=float(word_count),
            flags=["Short answer - natural speech characteristics"],
            verdict="Likely Human (short response)"
        )

    # 1. Compute per-sentence metrics
    sentence_lengths = [len(re.findall(r'\b[a-zA-Z]+\b', s)) for s in sentences]
    sentence_ppls = [calculate_sentence_perplexity(s) for s in sentences]

    avg_length = sum(sentence_lengths) / len(sentence_lengths)
    avg_ppl = sum(sentence_ppls) / len(sentence_ppls)
    burstiness = calculate_burstiness(sentence_lengths, sentence_ppls)

    # 2. Check for AI Hallmark Cliches
    flags = []
    detected_cliches = 0
    lower_text = text.lower()
    for pattern in LLM_MARKERS:
        matches = re.findall(pattern, lower_text)
        if matches:
            detected_cliches += len(matches)
            flags.append(f"Detected AI transition/cliché: '{matches[0]}'")

    # 3. Assess Burstiness Indicators
    if burstiness < 0.22 and len(sentences) >= 3:
        flags.append("Extremely uniform sentence rhythm (Low Burstiness - strong AI signature)")
    elif burstiness < 0.32 and len(sentences) >= 2:
        flags.append("Even sentence length pacing (Moderate-Low Burstiness)")
    elif burstiness > 0.55:
        flags.append("Natural varied sentence rhythm (High Burstiness - human signature)")

    # 4. Assess Perplexity Indicators
    if avg_ppl < 26.0:
        flags.append("Highly predictable token sequences (Uniform Low Perplexity)")
    elif avg_ppl > 48.0:
        flags.append("High vocabulary unpredictability (Human-like varied perplexity)")

    # 5. Composite AI Probability Calculation
    # Low burstiness increases AI prob; High burstiness decreases it
    # Low perplexity increases AI prob; High perplexity decreases it
    # Cliches scale AI prob upwards
    score = 50.0  # Base neutral

    # Burstiness contribution (-25 to +25)
    if burstiness < 0.20:
        score += 25.0
    elif burstiness < 0.28:
        score += 15.0
    elif burstiness < 0.35:
        score += 5.0
    elif burstiness > 0.55:
        score -= 25.0
    elif burstiness >= 0.42:
        score -= 15.0
    elif burstiness >= 0.35:
        score -= 5.0

    # Perplexity contribution (-20 to +20)
    if avg_ppl < 24.0:
        score += 20.0
    elif avg_ppl < 28.0:
        score += 10.0
    elif avg_ppl > 50.0:
        score -= 20.0
    elif avg_ppl > 35.0:
        score -= 10.0
    elif avg_ppl >= 30.0:
        score -= 5.0

    # Cliche penalty (hallmark LLM transitions)
    if detected_cliches >= 3:
        cliche_boost = 35.0
    elif detected_cliches == 2:
        cliche_boost = 25.0
    elif detected_cliches == 1:
        cliche_boost = 12.0
    else:
        cliche_boost = 0.0
    score += cliche_boost

    # Bound probability between 2% and 98%
    ai_prob = max(2.0, min(98.0, round(score, 1)))
    human_score = round(100.0 - ai_prob, 1)
    is_flagged = ai_prob >= 60.0

    if is_flagged:
        if ai_prob >= 80.0:
            verdict = "High Likelihood of AI Generation (ChatGPT/Claude verbatim text)"
        else:
            verdict = "Moderate Likelihood of AI Assistance (assisted or polished)"
    else:
        if human_score >= 80.0:
            verdict = "High Likelihood of Human Authorship (organic conversational flow)"
        else:
            verdict = "Likely Human with consistent style"

    return AIDetectionResult(
        ai_probability=ai_prob,
        is_flagged=is_flagged,
        human_likeness_score=human_score,
        perplexity=round(avg_ppl, 1),
        burstiness=burstiness,
        sentence_count=len(sentences),
        avg_sentence_length=round(avg_length, 1),
        flags=flags,
        verdict=verdict
    )
