import io
import re
import time
from typing import Dict, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 760, "XHire Technical Evaluation Report")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(36, 754, 576, 754)
        # Footer
        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 25, footer_text)
        self.drawString(36, 25, "Confidential - Generated by XHire Autonomous Interview Platform")
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(36, 35, 576, 35)
        self.restoreState()

def generate_pdf_report(
    candidate_name: str,
    candidate_email: str,
    requisition_title: str,
    session_uuid: str,
    access_code: str,
    status: str,
    dar_data: Dict[str, Any]
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=45,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()
    
    # Custom Palette
    c_primary = colors.HexColor("#1e1b4b")   # deep indigo
    c_accent = colors.HexColor("#4f46e5")    # bright indigo
    c_dark = colors.HexColor("#0f172a")      # dark text
    c_muted = colors.HexColor("#64748b")     # muted gray
    c_success = colors.HexColor("#059669")   # emerald green
    c_border = colors.HexColor("#e2e8f0")    # border
    c_bg_light = colors.HexColor("#f8fafc")  # light background

    # Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=c_primary
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=13,
        textColor=c_muted
    )
    h2_style = ParagraphStyle(
        'Heading2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=c_primary,
        spaceBefore=14,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=c_dark
    )
    body_bold = ParagraphStyle(
        'BodyBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=13,
        textColor=c_dark
    )
    body_muted = ParagraphStyle(
        'BodyMuted',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=c_muted
    )
    callout_style = ParagraphStyle(
        'Callout',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9,
        leading=13,
        textColor=c_dark
    )

    story = []

    # 1. Header Banner
    header_data = [
        [
            Paragraph("<b>XHIRE</b> &bull; Autonomous Technical Screening", subtitle_style),
            Paragraph(f"Date: {time.strftime('%b %d, %Y')}", ParagraphStyle('RDate', parent=subtitle_style, alignment=2))
        ],
        [
            Paragraph("Technical Interview Evaluation Report", title_style),
            Paragraph(f"Status: <b>{status.upper()}</b>", ParagraphStyle('RStatus', parent=body_style, alignment=2, textColor=c_success if status in ('started', 'completed') else c_muted))
        ]
    ]
    t_header = Table(header_data, colWidths=[380, 160])
    t_header.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ('TOPPADDING', (0,0), (-1,-1), 2),
    ]))
    story.append(t_header)
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=c_accent, spaceBefore=0, spaceAfter=12))

    # 2. Candidate & Job Metadata Card
    meta_data = [
        [
            Paragraph("<b>Candidate:</b>", body_style),
            Paragraph(candidate_name, body_bold),
            Paragraph("<b>Position:</b>", body_style),
            Paragraph(requisition_title, body_bold)
        ],
        [
            Paragraph("<b>Email:</b>", body_style),
            Paragraph(candidate_email, body_style),
            Paragraph("<b>Access Code:</b>", body_style),
            Paragraph(f"<font color='#4f46e5'><b>{access_code}</b></font>", body_style)
        ],
        [
            Paragraph("<b>Session UUID:</b>", body_style),
            Paragraph(f"<font size='7'>{session_uuid}</font>", body_muted),
            Paragraph("<b>Evaluation Date:</b>", body_style),
            Paragraph(time.strftime('%Y-%m-%d %H:%M UTC'), body_style)
        ]
    ]
    t_meta = Table(meta_data, colWidths=[80, 190, 85, 185])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), c_bg_light),
        ('BOX', (0, 0), (-1, -1), 1, c_border),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, c_border),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 14))

    # 3. Executive KPI Scores (Hype vs. Reality)
    synthesis = dar_data.get('synthesis', {}) or {}
    resume_assess = dar_data.get('resume_assessment') or synthesis.get('resume_assessment') or {}
    
    interview_score = synthesis.get('final_score')
    resume_si = resume_assess.get('suitability_index')
    perf_gap = synthesis.get('performance_gap')

    score_str = f"{interview_score:.1f}%" if interview_score is not None else "In Progress"
    resume_str = f"{resume_si:.1f} / 5.0" if resume_si else "N/A"
    gap_str = f"{perf_gap:+.1f}%" if perf_gap is not None else "N/A"

    if interview_score is not None:
        if interview_score >= 80:
            verdict_str = "Strong Match (Recommended)"
        elif interview_score >= 65:
            verdict_str = "Qualified Match (Pass)"
        elif interview_score >= 50:
            verdict_str = "Borderline (Needs Review)"
        else:
            verdict_str = "Not Recommended (Gap Detected)"
    else:
        verdict_str = resume_assess.get('verdict', 'Under Evaluation')

    kpi_data = [
        [
            Paragraph("<font size='8' color='#64748b'>INTERVIEW SCORE (PROOF)</font>", body_style),
            Paragraph("<font size='8' color='#64748b'>RESUME INDEX (CLAIM)</font>", body_style),
            Paragraph("<font size='8' color='#64748b'>PERFORMANCE GAP</font>", body_style),
            Paragraph("<font size='8' color='#64748b'>RECOMMENDATION VERDICT</font>", body_style)
        ],
        [
            Paragraph(f"<font size='15' color='#4f46e5'><b>{score_str}</b></font>", body_style),
            Paragraph(f"<font size='15' color='#0f172a'><b>{resume_str}</b></font>", body_style),
            Paragraph(f"<font size='15' color='#059669'><b>{gap_str}</b></font>", body_style),
            Paragraph(f"<font size='11' color='#1e1b4b'><b>{verdict_str}</b></font>", body_style)
        ]
    ]
    t_kpi = Table(kpi_data, colWidths=[130, 130, 120, 160])
    t_kpi.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
        ('BOX', (0, 0), (-1, -1), 1, c_border),
        ('LINEAFTER', (0, 0), (2, -1), 1, c_border),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t_kpi)
    story.append(Spacer(1, 14))

    # 4. AI Evaluation Summary
    raw_ai_summary = synthesis.get('summary') or "Interview evaluation is currently in progress. Full synthesis summary will be generated once all technical rounds are concluded."
    ai_summary = re.sub(r'<[^>]+>', '', raw_ai_summary).strip()
    story.append(Paragraph("Executive Evaluation Summary", h2_style))
    summary_table = Table([[Paragraph(ai_summary, callout_style)]], colWidths=[540])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 12))

    # 5. Technical Category Scores & Depth Analysis
    radar_data = synthesis.get('radar_data') or {}
    categories_dar = dar_data.get('categories') or {}
    
    cat_rows = [
        [
            Paragraph("<b>Category / Domain</b>", body_bold),
            Paragraph("<b>Assigned Interviewer</b>", body_bold),
            Paragraph("<b>Subtopics Assessed</b>", body_bold),
            Paragraph("<b>Score</b>", body_bold)
        ]
    ]

    if categories_dar:
        for cname, cdata in categories_dar.items():
            if cname == "Intro":
                continue
            assigned_agent = cdata.get('assigned_agent', 'Technical Interviewer')
            subtopics = cdata.get('subtopics', {})
            subtopic_names = ", ".join(list(subtopics.keys())[:3])
            score_val = radar_data.get(cname, "Pending")
            score_display = f"{score_val}%" if isinstance(score_val, (int, float)) else str(score_val)
            cat_rows.append([
                Paragraph(cname, body_bold),
                Paragraph(assigned_agent, body_style),
                Paragraph(subtopic_names, body_style),
                Paragraph(score_display, body_bold)
            ])
    else:
        cat_rows.append([Paragraph("Engineering Leadership & Fundamentals", body_style), Paragraph("ManagerInterviewer", body_style), Paragraph("Technical Background, Collaboration", body_style), Paragraph("Pending", body_style)])

    t_cat = Table(cat_rows, colWidths=[180, 130, 160, 70])
    t_cat.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
        ('BOX', (0, 0), (-1, -1), 1, c_border),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, c_border),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(Paragraph("Category Competence & Domain Breakdown", h2_style))
    story.append(t_cat)
    story.append(Spacer(1, 14))

    # 6. Resume Pillar Assessment (if available)
    pillar_scores = resume_assess.get('pillar_scores', [])
    if pillar_scores:
        story.append(Paragraph("Resume Pillar Analysis (Claim Assessment)", h2_style))
        p_rows = [
            [
                Paragraph("<b>Evaluation Pillar</b>", body_bold),
                Paragraph("<b>Score (/ 5.0)</b>", body_bold),
                Paragraph("<b>Assessment Rationale</b>", body_bold)
            ]
        ]
        for p in pillar_scores:
            p_rows.append([
                Paragraph(p.get('pillar', 'General'), body_bold),
                Paragraph(f"{p.get('score', 0):.1f}", body_style),
                Paragraph(p.get('rationale', ''), body_style)
            ])
        t_pillars = Table(p_rows, colWidths=[150, 70, 320])
        t_pillars.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
            ('BOX', (0, 0), (-1, -1), 1, c_border),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, c_border),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(t_pillars)
        story.append(Spacer(1, 14))

    # 7. Interview Q&A Transcript & AI Evaluation Log
    log_items = dar_data.get('interview_log', [])
    if log_items:
        story.append(Paragraph("Interview Question & Answer Transcript", h2_style))
        for idx, item in enumerate(log_items, 1):
            q_text = item.get('question') or "(No question recorded)"
            a_text = item.get('user_answer') or "(Pending answer)"
            agent_name = item.get('agent') or "Interviewer"
            category = item.get('category') or "General"
            subtopic = item.get('subtopic') or "General"
            res = item.get('result') or {}
            rationale = res.get('rationale') or "Response logged."
            conf_delta = res.get('confidence_delta', 0)
            delta_str = f"{conf_delta:+d} confidence" if conf_delta else "Introductory"

            qa_data = [
                [
                    Paragraph(f"<b>Q{idx} &bull; {agent_name}</b> ({category} &rarr; {subtopic})", body_bold),
                    Paragraph(f"<font color='#64748b' size='8'>Score: <b>{delta_str}</b></font>", ParagraphStyle('RScore', parent=body_style, alignment=2))
                ],
                [
                    Paragraph(f"<b>Question:</b> {q_text}", body_style),
                    ""
                ],
                [
                    Paragraph(f"<b>Candidate Answer:</b> <i>{a_text}</i>", body_style),
                    ""
                ],
                [
                    Paragraph(f"<b>AI Assessment:</b> {rationale}", ParagraphStyle('Rat', parent=body_style, textColor=colors.HexColor("#334155"))),
                    ""
                ]
            ]
            t_qa = Table(qa_data, colWidths=[420, 120])
            t_qa.setStyle(TableStyle([
                ('SPAN', (0, 1), (1, 1)),
                ('SPAN', (0, 2), (1, 2)),
                ('SPAN', (0, 3), (1, 3)),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('BOX', (0, 0), (-1, -1), 0.75, c_border),
                ('LINEBELOW', (0, 0), (-1, 0), 0.5, c_border),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(KeepTogether([t_qa, Spacer(1, 8)]))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()